-- AlterTable
ALTER TABLE "Portfolio" ADD COLUMN     "totalPnl" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "totalPnlPercent" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "totalValue" DECIMAL(65,30) NOT NULL DEFAULT 10000.00;
