-- AlterTable
ALTER TABLE "Asset" ADD COLUMN     "askPrice" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "bidPrice" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "midPrice" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "quoteTimestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "quoteVolume" DECIMAL(65,30) NOT NULL DEFAULT 0;

-- DropEnum
DROP TYPE "TimeframeType";
