export const actifs = [
    {
        description: 'Apple Inc',
        symbol: 'AAPL',
        logo: 'default-logo.png',
        sectorActivity: 'Technology',
        type: 'Stock',
        current_price: 0,
        highest_price_day: 0,
        lowest_price_day: 0,
        opening_price_day: 0,
        previous_close_price_day: 0,
        percent_change: 0,
        change: 0,
    },
    {
        description: 'MICROSOFT CORP',
        symbol: 'MSFT',
        logo: 'default-logo.png',
        sectorActivity: 'Technology',
        type: 'Stock',
        current_price: 0,
        highest_price_day: 0,
        lowest_price_day: 0,
        opening_price_day: 0,
        previous_close_price_day: 0,
        percent_change: 0,
        change: 0,
    },
    {
        description: 'ALPHABET INC-CL A',
        symbol: 'GOOGL',
        logo: 'default-logo.png',
        sectorActivity: 'Technology',
        type: 'Stock',
        current_price: 0,
        highest_price_day: 0,
        lowest_price_day: 0,
        opening_price_day: 0,
        previous_close_price_day: 0,
        percent_change: 0,
        change: 0,
    },
    {
        description: 'SPDR S&P 500 ETF TRUST',
        symbol: 'SPY',
        logo: 'default-logo.png',
        sectorActivity: 'ETF',
        type: 'ETF',
        current_price: 0,
        highest_price_day: 0,
        lowest_price_day: 0,
        opening_price_day: 0,
        previous_close_price_day: 0,
        percent_change: 0,
        change: 0,
    },
    {
        description: 'INVESCO QQQ TRUST SERIES 1',
        symbol: 'QQQ',
        logo: 'default-logo.png',
        sectorActivity: 'ETF',
        type: 'ETF',
        current_price: 0,
        highest_price_day: 0,
        lowest_price_day: 0,
        opening_price_day: 0,
        previous_close_price_day: 0,
        percent_change: 0,
        change: 0,
    },
];
